name: devcert
services:
  nginx:
    image: nginx
    volumes:
      - ./.devcert/devcert.crt:/etc/nginx/certs/devcert.crt:ro
      - ./.devcert/devcert.key:/etc/nginx/certs/devcert.key:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
