server {
    listen 443 ssl;
    server_name devcert.localhost;

    ssl_certificate /etc/nginx/certs/devcert.crt;
    ssl_certificate_key /etc/nginx/certs/devcert.key;

    root /usr/share/nginx/html;
    index index.html;
}

server {
    listen 80;
    server_name devcert.localhost;

    return 301 https://$host$request_uri;
}
