use std::{
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{Context, Result};

/// Trust store implementation for Linux, supporting multiple distributions.
pub struct LinuxTrustStore {
    /// Stable ID for the CA certificate, used in naming and tracking.
    id: String,
    /// Path to the CA certificate file generated by DevCert.
    cert_path: PathBuf,
    /// Detected Linux distribution, used to determine trust store conventions.
    distro: Distro,
}

impl LinuxTrustStore {
    /// Creates a new `LinuxTrustStore` instance for the given CA certificate.
    pub fn new(id: &String, cert_path: &PathBuf) -> Self {
        Self {
            id: id.clone(),
            cert_path: cert_path.clone(),
            distro: Distro::detect(),
        }
    }

    /// Returns whether the cert is global or project-specific depending on the id.
    fn cert_type(&self) -> &'static str {
        if self.id.starts_with("global") {
            "Global"
        } else {
            "Project"
        }
    }

    /// Full path where the certificate will be written in the system store.
    fn cert_path(&self) -> Option<PathBuf> {
        let dir = self.distro.cert_dir()?;
        let name = format!("devcert-{}", self.id);

        Some(PathBuf::from(format!(
            "{}{}.{}",
            dir,
            name,
            self.distro.cert_extension()
        )))
    }

    /// Runs a command under `sudo` and checks the exit status.
    fn sudo_run(&self, args: &[&str]) -> Result<()> {
        let status = Command::new("sudo")
            .args(args)
            .status()
            .with_context(|| format!("Failed to run: sudo {}", args.join(" ")))?;

        if !status.success() {
            anyhow::bail!("Command failed: sudo {}", args.join(" "));
        }

        Ok(())
    }

    /// Writes `content` to `dest` using `sudo tee`, avoiding a temp-file copy.
    fn sudo_write(&self, dest: &Path, content: &[u8]) -> Result<()> {
        let mut child = Command::new("sudo")
            .args(["tee", &dest.to_string_lossy()])
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .spawn()
            .context("Failed to spawn sudo tee — is sudo available?")?;

        child
            .stdin
            .take()
            .context("Could not open stdin for sudo tee")?
            .write_all(content)
            .context("Failed to pipe certificate content to sudo tee")?;

        let status = child.wait().context("sudo tee exited unexpectedly")?;

        if !status.success() {
            anyhow::bail!("sudo tee failed — do you have the required privileges?");
        }

        Ok(())
    }

    /// Updates the system trust store after adding or removing a certificate.
    fn refresh_trust_store(&self) -> Result<()> {
        if let Some(cmd) = self.distro.update_command() {
            self.sudo_run(&cmd)
                .context("Failed to refresh the system trust store")?;
        }

        Ok(())
    }
}

/// Supported Linux distributions and their trust store conventions.
#[derive(Debug, Clone, Copy, PartialEq)]
enum Distro {
    Arch,
    Debian,
    RedHat,
    OpenSUSE,
    Unknown,
}

impl Distro {
    /// Detects the current Linux distribution by probing well-known paths.
    fn detect() -> Self {
        let checks: &[(&str, Distro)] = &[
            ("/etc/ca-certificates/trust-source/anchors/", Distro::Arch),
            ("/usr/local/share/ca-certificates/", Distro::Debian),
            ("/etc/pki/ca-trust/source/anchors/", Distro::RedHat),
            ("/usr/share/pki/trust/anchors/", Distro::OpenSUSE),
        ];

        for (path, distro) in checks {
            if Path::new(path).exists() {
                return *distro;
            }
        }

        Distro::Unknown
    }

    /// Directory where the certificate should be placed.
    fn cert_dir(&self) -> Option<&'static str> {
        match self {
            Distro::Arch => Some("/etc/ca-certificates/trust-source/anchors/"),
            Distro::Debian => Some("/usr/local/share/ca-certificates/"),
            Distro::RedHat => Some("/etc/pki/ca-trust/source/anchors/"),
            Distro::OpenSUSE => Some("/usr/share/pki/trust/anchors/"),
            Distro::Unknown => None,
        }
    }

    /// File extension expected by this distribution's trust tooling.
    fn cert_extension(&self) -> &'static str {
        match self {
            Distro::RedHat | Distro::OpenSUSE => "pem",
            Distro::Debian | Distro::Arch => "crt",
            Distro::Unknown => "pem",
        }
    }

    /// Command and arguments needed to refresh the system trust store.
    fn update_command(&self) -> Option<Vec<&'static str>> {
        match self {
            Distro::Arch => Some(vec!["trust", "extract-compat"]),
            Distro::Debian | Distro::OpenSUSE => Some(vec!["update-ca-certificates"]),
            Distro::RedHat => Some(vec!["update-ca-trust", "extract"]),
            Distro::Unknown => None,
        }
    }
}
